### ISSUE TITLE
test-system 2 failures on lispworks7

### ISSUE THREAD

**Issue by albuspiroglu** [sionescu/bordeaux-threads#99]
Running (asdf:test-system "bordeaux-threads") fails two cases with message:

> Did 85 checks.
>     Pass: 83 (97%)
>     Skip: 0 ( 0%)
>     Fail: 2 ( 2%)
>  Failure Details:
>  --------------------------------
>  SEMAPHORE.SIGNAL-N-OF-M in BORDEAUX-THREADS-2 []:    
> 4 evaluated to 4 which is not = to 2
>  --------------------------------
>  SEMAPHORE.SIGNAL-N-OF-M in BORDEAUX-THREADS-2 []: 
> 5 evaluated to 5 which is not = to 3

**Comment by sionescu** [comment]
I pushed a few changes to the tests. Can you please run the test suite again ?

**Comment by albuspiroglu** [comment]
New run, results same failures:

 Did 88 checks.
    Pass: 86 (97%)
    Skip: 0 ( 0%)
    Fail: 2 ( 2%)
 Failure Details:
 
 SEMAPHORE.SIGNAL-N-OF-M in BORDEAUX-THREADS-2 []:       
COUNT
 evaluated to 2 which is not = to 4
 
 SEMAPHORE.SIGNAL-N-OF-M in BORDEAUX-THREADS-2 []: 
COUNT
 evaluated to 3 which is not = to 5

**Comment by albuspiroglu** [comment]
I've been checking some details, and it seems like when we run the failing test, the threads 3&4 never return. 0,1,2 do. But then the first count should've been 3, not 2. When I print the count from the waiter thread, all three prints the incremented count, so it seems somehow the let - count isn't the same as thread - count? I still don't see what's happening.

**Comment by Yehouda** [comment]
That isa bug in LispWorks (I just fixed in our development sources).

**Comment by sionescu** [comment]
That's excellent! Dow you expect to make a bugfix release any time soon ?

**Comment by Yehouda** [comment]
We will want to make sure it doesn;t break too many things first. Probably next patch release.

**Comment by sionescu** [comment]
@Yehouda was a fix released ?

**Comment by Yehouda** [comment]
It is mp.1.2, which is part of the first patch release of LW 8.0, so it should work in Lw 8.0.1.

http://www.lispworks.com/downloads/patch-selection.html

**Comment by sionescu** [comment]
Alright, thank you. I'm closing this issue as fixed.
